name: CI devops 2025

on:
  # Lancer le job sur les branches main et develop
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend: 
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : récupérer le code depuis le dépôt
      - uses: actions/checkout@v4

      # Étape 2 : configurer le JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : compiler et tester l'application
      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml
