name: Test backend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml

      - name: SonarCloud analysis
        run: mvn verify sonar:sonar \
          -Dsonar.projectKey=mehdisaadiiii_TP2-DevOPs \
          -Dsonar.organization=mehdisaadiiii92 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          --file simple-api/pom.xml
